package qaautomation.december2022.api.schemalist;

public class SchemaSignUp {
	public String signupSchema() {
		String s = "{\n"
				+ "  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n"
				+ "  \"type\": \"object\",\n"
				+ "  \"properties\": {\n"
				+ "    \"completed_build_card\": {\n"
				+ "      \"type\": \"array\",\n"
				+ "      \"items\": {}\n"
				+ "    },\n"
				+ "    \"build_card_count\": {\n"
				+ "      \"type\": \"object\",\n"
				+ "      \"properties\": {\n"
				+ "        \"project_completed\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"completed\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"incomplete\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"running\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"invited\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"archived\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"prototype\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"custom_prototype\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"tailor_made_prototype\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        },\n"
				+ "        \"freemium\": {\n"
				+ "          \"type\": \"integer\"\n"
				+ "        }\n"
				+ "      },\n"
				+ "      \"required\": [\n"
				+ "        \"project_completed\",\n"
				+ "        \"completed\",\n"
				+ "        \"incomplete\",\n"
				+ "        \"running\",\n"
				+ "        \"invited\",\n"
				+ "        \"archived\",\n"
				+ "        \"prototype\",\n"
				+ "        \"custom_prototype\",\n"
				+ "        \"tailor_made_prototype\",\n"
				+ "        \"freemium\"\n"
				+ "      ]\n"
				+ "    }\n"
				+ "  },\n"
				+ "  \"required\": [\n"
				+ "    \"completed_build_card\",\n"
				+ "    \"build_card_count\"\n"
				+ "  ]\n"
				+ "}";
		return s;
	}
}
